#!/bin/bash
set -e
version=$(curl -s https://api.github.com/repos/helm/helm/releases/latest  | jq -r '.tag_name')
curl -sL "https://get.helm.sh/helm-$version-linux-amd64.tar.gz" \
    | tar -C $HOME/.local/bin -xz --strip-components=1 --mode=0755 \
    linux-amd64/helm

bashcompdir=$HOME/.local/share/bash-completion/completions
[[ -d $bashcompdir ]] || mkdir -p $bashcompdir
bashcomp=$bashcompdir/helm
helm completion bash  > $bashcomp
chmod 0644 $bashcomp
