#!/bin/bash
set -e
version="v3.8.1"
curl -sL "https://get.helm.sh/helm-$version-linux-amd64.tar.gz" \
    | tar -C $HOME/.local/bin -xz --strip-components=1 --mode=0755 \
    linux-amd64/helm

bashcompdir=$HOME/.local/share/bash-completion/completions
[[ -d $bashcompdir ]] || mkdir -p $bashcompdir
bashcomp=$bashcompdir/_helm
helm completion bash  > $bashcomp
chmod 0644 $bashcomp
