#!/bin/bash

version=$(curl -s https://api.github.com/repos/derailed/k9s/releases/latest  | jq -r '.tag_name')
set -e
curl -L https://github.com/derailed/k9s/releases/download/${version}/k9s_Linux_amd64.tar.gz \
	| tar -C $HOME/.local/bin -xz --mode=0755 k9s
