#!/bin/bash

APP_VER=7.5
APP_DIR=$HOME/.local/opt/sh3d
APP_NAME=sh3d
MODELS_VER=1.9.3
TEXTURES_VER=1.3.1
ICON_DIR=$HOME/.local/share/icons

[[ -d $APP_DIR ]] || mkdir -p $APP_DIR

curl -L -o ${APP_DIR}/${APP_NAME}.jar \
     https://sourceforge.net/projects/sweethome3d/files/SweetHome3D/SweetHome3D-${APP_VER}/SweetHome3D-${APP_VER}.jar/download

[[ -d $ICON_DIR ]] || mkdir -p $ICON_DIR
curl -L -o $HOME/.local/share/icons/sh3d.png https://www.sweethome3d.com/blog/images/5.2/SweetHome3DIcon512x512.png

declare -A LIBS=(
    ["model-contributions"]="https://sourceforge.net/projects/sweethome3d/files/SweetHome3D-models/3DModels-${MODELS_VER}/3DModels-Contributions-${MODELS_VER}.zip/download"
    ["model-contributions"]="https://sourceforge.net/projects/sweethome3d/files/SweetHome3D-models/3DModels-${MODELS_VER}/3DModels-Contributions-${MODELS_VER}.zip/download"
    ["model-blendswap-cc"]="https://sourceforge.net/projects/sweethome3d/files/SweetHome3D-models/3DModels-${MODELS_VER}/3DModels-BlendSwap-CC-0-${MODELS_VER}.zip/download"
    ["model-blendswap-ccby"]="https://sourceforge.net/projects/sweethome3d/files/SweetHome3D-models/3DModels-${MODELS_VER}/3DModels-BlendSwap-CC-BY-${MODELS_VER}.zip/download"
    ["model-katorlegaz"]="https://sourceforge.net/projects/sweethome3d/files/SweetHome3D-models/3DModels-${MODELS_VER}/3DModels-KatorLegaz-${MODELS_VER}.zip/download"
    ["model-lucapresidente"]="https://sourceforge.net/projects/sweethome3d/files/SweetHome3D-models/3DModels-${MODELS_VER}/3DModels-LucaPresidente-${MODELS_VER}.zip/download"
    ["model-reallusion"]="https://sourceforge.net/projects/sweethome3d/files/SweetHome3D-models/3DModels-${MODELS_VER}/3DModels-Reallusion-${MODELS_VER}.zip/download"
    ["model-scopia"]="https://sourceforge.net/projects/sweethome3d/files/SweetHome3D-models/3DModels-${MODELS_VER}/3DModels-Scopia-${MODELS_VER}.zip/download"
    ["model-trees"]="https://sourceforge.net/projects/sweethome3d/files/SweetHome3D-models/3DModels-${MODELS_VER}/3DModels-Trees-${MODELS_VER}.zip/download"
    ["textures-contributions"]="https://sourceforge.net/projects/sweethome3d/files/SweetHome3D-textures/Textures-${TEXTURES_VER}/Textures-Contributions-${TEXTURES_VER}.zip/download"
    ["textures-eteksscopia"]="https://sourceforge.net/projects/sweethome3d/files/SweetHome3D-textures/Textures-${TEXTURES_VER}/Textures-eTeksScopia-${TEXTURES_VER}.zip/download"
)

for lib in ${!LIBS[@]}; do
    echo "Downloading $lib..."
    curl -L -# -o "${lib}.zip" "${LIBS[$lib]}"
    echo "Unzipping $lib..."
    unzip "${lib}.zip" '*.sh3*' && rm "${lib}.zip"
done

cat <<EOF > ~/.local/share/applications/sh3d.desktop
[Desktop Entry]
Type=Application
Version=1.0
Name=Sweet Home 3D
Path=$APP_DIR
Exec=java -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel -jar sh3d.jar
Icon=sh3d
EOF
