#!/bin/bash
set -e

version=$(curl -s https://api.github.com/repos/tilt-dev/tilt/releases/latest  | jq -r '.tag_name')
curl -L https://github.com/tilt-dev/tilt/releases/download/${version}/tilt.${version:1}.linux.x86_64.tar.gz \
	| tar -C $HOME/.local/bin -xz --mode=0755 tilt

bashcompdir=$HOME/.local/share/bash-completion/completions
[[ -d $bashcompdir ]] || mkdir -p $bashcompdir
bashcomp=$bashcompdir/tilt
tilt completion bash  > $bashcomp
chmod 0644 $bashcomp
