# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

if [[ -n $WSL_DISTRO_NAME ]]; then
  # Probably it's WSL
  export TERM=xterm-256color
  export COLORTERM=truecolor
fi

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

function ps_aws_profile() {
    echo "${AWS_PROFILE:-default}"
}

function ps_k8s_context() {
    local kubeconfig=${KUBECONFIG:-~/.kube/config}
    local cachefile=~/.cache/ps/k8s_context

    if [[ ! -r $kubeconfig ]]; then
        echo "-"
    elif [[ $cachefile -nt $kubeconfig ]]; then
        cat $cachefile
    else
        local ctx=$(kubectl config current-context)
        echo $ctx | tee $cachefile
    fi
}

function ps_git() {
    local psgit=$(__git_ps1 %s)
    if [[ -n $psgit ]]; then
        echo "$psgit"
    else
        echo "-"
    fi
}

export EDITOR=vim

PROMPT_DIRTRIM=2
# ┏ ┗
PS1="┌ \[\e[1;34m\]aws:\[\e[39m\]\[\$(ps_aws_profile)\]\[\e[0m\]"
PS1="$PS1 \[\e[1;34m\]k8s:\[\e[39m\]\[\$(ps_k8s_context)\]\[\e[0m\]"
PS1="$PS1 \[\e[1;34m\]git:\[\e[39m\]\[\$(ps_git)\]\[\e[0m\]"
PS1="$PS1\n└ \[\e[1;34m\]\w\[\e[0m\] \[\e[01;32m\]❯\[\e[0m\] "

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

alias e='emacs -nw'

eval "$(direnv hook bash)"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
