if [[ -z $TMUX ]]; then
    if [[ -d $HOME/.local/bin ]]; then
        PATH=$HOME/.local/bin:$PATH
    fi

    if [[ -d $HOME/.bash_profile.d ]]; then
        for f in $HOME/.bash_profile.d/*.sh; do
            source $f
        done
    fi
fi

if [[ -f $HOME/.bashrc ]]; then
    source $HOME/.bashrc
fi
